### ISSUE TITLE
database.sh timeout

### ISSUE THREAD

**Issue by EMPTYVOID-DEV** [EMPTYVOID-DEV/Studies#2]
how to add a timeout to user input which will cause the script but at the same time reset the timeout when receiving an input.

read -t does not work there is a solution using tty configuration.

**Comment by hdood** [comment]
when the read command finishes by timeout the exit code will be 1 so we can use the variable $? to the last command exit code and we can test that variable so we can do something like this : 

`function terminate_if_inactive(){

    if [ $? -ne 0 ]; then

        echo script terminated for inactivity
        exit 0

    fi

	
}`
And put this function after every read command that we want it to have a time out.

**Comment by Shinji13** [comment]
this is not what i meant i want to reset the timeout after each key stroke
